"""Create column Update_at projects table

Revision ID: 287870f9e15e
Revises: 26c8609dd4db
Create Date: 2025-08-20 18:31:39.700674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "287870f9e15e"
down_revision: Union[str, Sequence[str], None] = "26c8609dd4db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "updated_at")
    # ### end Alembic commands ###
